name: ocli-sfdc
base: core22
version: git
summary: Command-line interface for Salesforce
description: |
  sfdc is a CLI for interacting with Salesforce.

  Features:
  - OAuth 2.0 authentication with secure token storage
  - SOQL queries with table, JSON, and plain output
  - Object CRUD operations
  - API discovery and metadata inspection

  Run 'sfdc init' to configure OAuth authentication.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  dot-config-salesforce-cli:
    interface: personal-files
    read:
      - $HOME/.config/salesforce-cli
    write:
      - $HOME/.config/salesforce-cli

apps:
  ocli-sfdc:
    command: bin/sfdc
    plugs:
      - home
      - network
      - dot-config-salesforce-cli
    aliases:
      - sfdc

parts:
  sfdc:
    plugin: go
    source: .
    build-snaps:
      - go/1.24/stable
    build-environment:
      - CGO_ENABLED: "0"
    override-build: |
      # Get version from git
      VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
      COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
      DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

      # Build with ldflags
      go build -o $SNAPCRAFT_PART_INSTALL/bin/sfdc \
        -ldflags "-s -w \
          -X github.com/open-cli-collective/salesforce-cli/internal/version.Version=${VERSION} \
          -X github.com/open-cli-collective/salesforce-cli/internal/version.Commit=${COMMIT} \
          -X github.com/open-cli-collective/salesforce-cli/internal/version.BuildDate=${DATE}" \
        ./cmd/sfdc
